name: PassWifi
on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'The Wifi to test, provided by the web UI'
        required: true
        default: 'http://example.com'
jobs:
  certapple-run:
    name: Run Passwifi Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Passwifi test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ðŸ’¹ðŸ’¹ðŸ’¹Passwifi.js
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
